Hc 60 룸메이트 신청 모달
house-mate-connect/house-connect pull request #20
Opened 2024-05-22 07:18 UTC by siuhyun

## 📝 개요(이미지 첨부 선택)
`RoommateApply` Modal 구현

|`RoommateApply Modal`|
|:---:|
|<img width="645" alt="스크린샷 2024-05-21 오전 12 19 33" src="https://github.com/house-mate-connect/house-connect/assets/149446617/88ed3db9-43c2-4be3-8233-a8db9cf94ebd">

---
### 전역상태로 선택된 모달만 관리
### 1️⃣ 어떤 component에서도 modal에 접근하기 쉽게 각 modal에 대한 정보를 `전역 상태`로 구현

```typescript
// src/stores/globalModal.store.ts

export const RoommateApplyAtom = atom<RoommateApplyState>({
  key: 'RoommateApplyState',
  default: {
    isOpen: false,
    type: 'RoommateApply',
    introduceContent: '',
    roommateAppeals: [],
    onClickCancel: () => {},
    onClickConfirm: () => {},
  },
});
```
### 2️⃣ GlobalModal에서 룸메이트 신청 모달 전역 상태 정의
```typescript
// src/components/templates/GlobalModal.tsx

export default function GlobalModal() {
  const modalType = useRecoilValue(GlobalModalAtom);

  // eslint-disable-next-line react-refresh/only-export-components
  const TypesOfModals = {
    Alert: AlertModal,
    Confirm: ConfirmModal,
    Profile: ProfileModal,
    RoommateApply: RoommateApplyModal,
  };

  const SelectedModal = TypesOfModals[modalType];

  return <SelectedModal />;
}
```
---
`modalType`에 따라 state getter, setter를 `selectorFamily`로 구현된 로직에 RoommateApply 추가

```typescript
// src/stores/globalModal.store.ts

export const ModalSelector = selectorFamily({
  key: 'modalPropsByType',
  get:
    <P extends ModalType>(modalType: P) =>
    ({ get }) => {
      switch (modalType) {
        case 'Alert':
          return get(AlertModalAtom) as ModalStateByType[P];
        case 'Confirm':
          return get(ConfirmModalAtom) as ModalStateByType[P];
        case 'Profile':
          return get(ProfileModalAtom) as ModalStateByType[P];
        case 'RoommateApply':
          return get(RoommateApplyAtom) as ModalStateByType[P];
        default:
          errorSelector('Undefined cannot be a value of ModalType.');
          throw new Error('Undefined cannot be a value of ModalType.');
      }
    },
  set:
    <P extends ModalType>(modalType: P) =>
    ({ set }, newModalState) => {
      switch (modalType) {
        case 'Alert':
          set(AlertModalAtom, newModalState as AlertModalState);
          break;
        case 'Confirm':
          set(ConfirmModalAtom, newModalState as ConfirmModalState);
          break;
        case 'Profile':
          set(ProfileModalAtom, newModalState as ProfileModalState);
          break;
        case 'RoommateApply':
          set(RoommateApplyAtom, newModalState as RoommateApplyState);
          break;

        default:
          // eslint-disable-next-line no-console
          errorSelector(`Received unexpected modal type: ${modalType}`);
          throw new Error(`Received unexpected modal type: ${modalType}`);
      }
    },
});
```
---

### 3️⃣ Modal Usage
```typescript
// src/components/pages/ComponentTest.tsx
export default function ComponentTest() {
const {
    setModalState: setRoommateApplyModal,
    closeModal: closeRoommateApplyModal,
  } = useModal('RoommateApply');
  const RoommateApplyModalContext: RoommateApplyState = {
    isOpen: true,
    type: 'RoommateApply',
    introduceContent: '',
    roommateAppeals: [
      '1명',
      '남성',
      '잠귀 어두운 분',
      '청소 자주해요',
      '늦게 자요',
    ],
    onClickCancel: () => {
      closeRoommateApplyModal();
    },
    onClickConfirm: () => {
      alert('Completed Apply');
      closeRoommateApplyModal();
    },
  };

 return (
  ... //
   <button
        type="button"
        className="mb-10"
        onClick={() => setRoommateApplyModal(RoommateApplyModalContext)}
      >
        Roommate modal 열기
  </button>
  ... // 
  )
}
```

## ✅ PR 유형
어떤 변경 사항이 있나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [x] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [x] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## 📌 PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.  
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
- [ ] 모든 팀원이 PR에 대한 리뷰를 진행했습니다.
- [x] 이 코드 변경 사항은 기존 기능에 영향을 주지 않나요?
- [x] 팀원이 이해할 수 있도록 충분한 주석 및 코드 일관성을 준수했나요? (변수명, 함수명, 클래스명, 가독성 등)

## 💁‍♂️ PR 추가 정보
**

2024-05-22 07:45 UTC, kwondns requested changes
댓글 확인 후 수정부탁드려요

2024-05-22 07:45 UTC, kwondns commented on src/components/templates/GlobalModal.tsx
> +import RoommateApplyModal from '../organisms/modals/RoommateApplyModal';
alias path 사용해주세요

2024-05-22 07:45 UTC, kwondns commented on src/components/organisms/modals/RoommateApplyModal.tsx
> +    const newInroduceContent = e.currentTarget.value;
```ts
const {value: newIntroduceContent} = e.currentValue
```

이렇게 작성하는게 좋겠네요

그리고 Inroduce <- 오타있어요

2024-05-22 07:45 UTC, kwondns commented on src/components/organisms/modals/RoommateApplyModal.tsx
> +                placeholder="나를 소개하는 글을 작성해보세요."
최대 250자라고 명시했는데 250자 제한하는 부분이 없네요

2024-05-22 13:38 UTC, rlwjd31 commented on src/components/templates/GlobalModal.tsx
> +import RoommateApplyModal from '../organisms/modals/RoommateApplyModal';
alias path vscode 기본 셋팅 해야 돼

2024-05-24 09:28 UTC, rlwjd31 approved these changes
고친 거 확인하고 PR 승인합니다~

2024-05-24 09:28 UTC, merged

2024-05-24 10:10 UTC, kwondns commented
오타 수정이랑 alias path 설정했나요?