[Merge] HC-31-UI-signup to dev
house-mate-connect/house-connect pull request #7
Opened 2024-05-02 08:33 UTC by New-Ha

## 📝 개요
SignUpIntroTemplate 의 UI를 디자인에 맞추어 구성하였습니다.

|Template1|Template2|
|---|---|
|<img width="960" alt="스크린샷 2024-05-02 오후 4 37 59" src="https://github.com/house-mate-connect/house-connect/assets/141496181/da8b732b-fb22-46ab-bac4-da354b3b3135">|<img width="960" alt="스크린샷 2024-05-02 오후 4 39 00" src="https://github.com/house-mate-connect/house-connect/assets/141496181/9b7ac8e9-317b-4fac-ad80-e18dc27546ec">|

## ✅ PR 유형
어떤 변경 사항이 있나요?
- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [X] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## 📌 PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.
- [X] 커밋 메시지 컨벤션에 맞게 작성했습니다.  
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
- [ ] 모든 팀원이 PR에 대한 리뷰를 진행했습니다.
- [X] 이 코드 변경 사항은 기존 기능에 영향을 주지 않습니다.
- [X] 팀원이 이해할 수 있도록 충분한 주석 및 코드 일관성을 준수했나요? (변수명, 함수명, 클래스명, 가독성 등)

## 💁‍♂️ PR 추가 정보
### 👀 차후 변경할 사항
- Template1의 주민등록번호 입력 필드를 Pin 입력처럼 각 숫자를 따로 받도록 UI 수정할 예정입니다.

2024-05-02 09:16 UTC, kwondns commented
Template1의 주민등록번호 입력 필드를 Pin 입력처럼 각 숫자를 따로 받도록 UI 수정할 예정입니다. -> Email 인증 입력을 Pin 입력

2024-05-02 09:21 UTC, kwondns commented on src/components/pages/SignUp.tsx
> +      <IconButton.Goast
Goast -> Ghost

2024-05-02 09:23 UTC, kwondns commented on src/components/organisms/Header.tsx
> +              <IconButton button="Ghost" iconType="alarm-exist" />
IconButton.Ghost 로 변경

2024-05-02 09:27 UTC, kwondns commented on src/components/templates/SignUpProfileLayout.template.tsx
> +const stepInfos = [
외부 분리하는 것이 좋을 듯?

2024-05-03 02:34 UTC, kwondns requested changes
코멘트 확인해주세요

2024-05-03 02:34 UTC, kwondns commented on src/components/molecules/StepNavigation.tsx
> +      className={cn('relative w-fit justify-between', className)}
Container 자체에 cn이 있으므로 불필요

2024-05-03 02:34 UTC, kwondns commented on src/components/pages/SignUpProfile.tsx
> +    // event?.preventDefault();
이런 주석은 지웁시다

2024-05-03 02:34 UTC, kwondns commented on src/components/templates/SignUpIntroTemplate1.tsx
> -              text="이메일"
FormItem.TextField를 사용해주세요

2024-05-03 02:34 UTC, kwondns commented on src/components/templates/SignUpIntroTemplate2.tsx
> +              <TextField
FormItem.TextField를 사용해주세요

2024-05-03 02:34 UTC, kwondns commented on src/components/templates/SignUpProfile1_2.template.tsx
>            {/* TODO Selector 변경 */}
완료한 TODO는 지워주세요

2024-05-03 02:34 UTC, kwondns commented on src/components/templates/SignUpProfile2_2.template.tsx
> +          <TextField<Pick<ProfileFormValues, 'appealsInputValue'>>
FormItem.TextField를 사용해주세요

2024-05-03 09:16 UTC, rlwjd31 approved these changes

2024-05-04 15:06 UTC, siuhyun approved these changes

2024-05-09 11:53 UTC, merged